FROM node:22-alpine

WORKDIR /app

# Cache otimizado
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force

# Copia código (volume sobrescreve em dev)
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
