FROM node:22-alpine

WORKDIR /app

# Cache deps
COPY package*.json ./
RUN npm ci

# Copia código
COPY . .

# Gera o client do Prisma
RUN npx prisma generate

# ← faltava essa linha
RUN npm run build

EXPOSE 8000