FROM node:22-alpine

WORKDIR /app

# Cache deps primeiro
COPY package*.json ./
RUN npm ci

# Copia código
COPY . .

# Prisma e build (adicione ao package.json se não tiver)
RUN npx prisma generate
RUN npm run build  # Opcional para prod

EXPOSE 3000

CMD ["npm", "run", "start:dev"]  # start:prod para produção
